### ISSUE TITLE
Class "Rawahamid\FibIntegration\Fib" not found

### ISSUE THREAD

**Issue by codenashwan** [rawahamid/laravel-fib-integration#4]
I am encountering an issue with my website's payment functionality when deploying it on a domain. The problem occurs specifically in the **production environment** and **not in localhost**. The error message I receive is : 

`Class "Rawahamid\FibIntegration\Fib" not found`

**To resolve this issue** :  it seems that the file name needs to match the one being called. Currently, the file is named "**FIB.php**" and I kindly request it to be renamed to "**Fib.php**" to ensure consistency. This file renaming should address the problem and allow the payment functionality to work correctly on the production domain.

Please let me know if any further information or assistance is needed to resolve this issue.

Please watch this video for more clarity: 

https://github.com/rawahamid/laravel-fib-integration/assets/35005761/a3cc1988-bbde-466f-869c-7f41c441f5ee

**Comment by rawahamid** [comment]
Solved
